#Link of the source dataset - in this case its the UCI repository
data_source: http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv

artifacts:
  artifacts_dir: artifacts
  raw_local_dir: raw_local_dir
  raw_local_file: data.csv